#!/bin/sh

export AUTH0_CLIENT_ID=

export AUTH0_CLIENT_SECRET=

export AUTH0_AUDIENCE=

export AUTH_V2_URL=

export AUTH_V2_CLIENT_ID=

export AUTH_V3_URL=

export ADMIN_CREDENTIALS_USERNAME=

export ADMIN_CREDENTIALS_PASSWORD=

export COPILOT_CREDENTIALS_USERNAME=

export COPILOT_CREDENTIALS_PASSWORD=

export USER_CREDENTIALS_USERNAME=

export USER_CREDENTIALS_PASSWORD=

export IS_LOCAL_DB=

export AUTH_SECRET=